_BASE_: "../yolov3-tiny.yaml"

SOLVER:
  REFERENCE_WORLD_SIZE: 8
  IMS_PER_BATCH: 16
  BASE_LR: 0.003
  STEPS: (2000, 5000)
  MAX_ITER: 8000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448)
  MIN_SIZE_TEST: 416