_BASE_: "../yolov3.yaml"

SOLVER:
  REFERENCE_WORLD_SIZE: 8
  IMS_PER_BATCH: 16
  BASE_LR: 0.003
  STEPS: (2000, 5000)
  MAX_ITER: 8000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MIN_SIZE_TEST: 448