_BASE_: "../yolov3.yaml"
MODEL:
  YOLOV3:
    NUM_CLASSES: 20
  BACKBONE:
    FREEZE_AT: 5  # freeze whole darknet53
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (12000, 16000)
  MAX_ITER: 20000
  WARMUP_ITERS: 200
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
TEST:
  EVAL_PERIOD: 6000
OUTPUT_DIR: "./output_voc_stage1"
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768)
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 640

  # Augmentation policy
  USE_YOLO_AUG: True
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.9, 0.9]
  JITTER_COLOR:
    ENABLED: True
    HSV_H: 0.015
    HSV_S: 0.7
    HSV_V: 0.4
  RANDOM_PERSPECTIVE:
    ENABLED: True
    DEGREES: 0.0
    TRANSLATE: 0.1
    SCALE: 0.2
    SHEER: 0.0
    PERSPECTIVE: 0.0
  MOSAIC:
    ENABLED:  True
    PATCH_SIZE: 544  # single image size
    POOL_SIZE: 2000

