_BASE_: "../yolov3-tiny.yaml"
MODEL:
  YOLOV3:
    NUM_CLASSES: 20
  BACKBONE:
    FREEZE_AT: 5
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (12000, 16000)
  MAX_ITER: 20000
  WARMUP_ITERS: 200
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512)
  MIN_SIZE_TEST: 416
TEST:
  EVAL_PERIOD: 6000