_BASE_: "../yolov3.yaml"
MODEL:
  YOLOV3:
    NUM_CLASSES: 20
  BACKBONE:
    FREEZE_AT: 0
  WEIGHTS: "./output_voc_stage1/model_final.pth"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  STEPS: (40000, 65000)
  MAX_ITER: 80000
  WARMUP_ITERS: 1000
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MIN_SIZE_TEST: 448
TEST:
  EVAL_PERIOD: 20000
OUTPUT_DIR: "./output_voc_stage2"